// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendMessageClient is the client API for SendMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMessageClient interface {
	SendTextMsg(ctx context.Context, in *TextMessage, opts ...grpc.CallOption) (*Response, error)
	SendMarkdownMsg(ctx context.Context, in *MarkdownMessage, opts ...grpc.CallOption) (*Response, error)
}

type sendMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMessageClient(cc grpc.ClientConnInterface) SendMessageClient {
	return &sendMessageClient{cc}
}

func (c *sendMessageClient) SendTextMsg(ctx context.Context, in *TextMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/SendMessage/SendTextMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendMessageClient) SendMarkdownMsg(ctx context.Context, in *MarkdownMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/SendMessage/SendMarkdownMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageServer is the server API for SendMessage service.
// All implementations must embed UnimplementedSendMessageServer
// for forward compatibility
type SendMessageServer interface {
	SendTextMsg(context.Context, *TextMessage) (*Response, error)
	SendMarkdownMsg(context.Context, *MarkdownMessage) (*Response, error)
	mustEmbedUnimplementedSendMessageServer()
}

// UnimplementedSendMessageServer must be embedded to have forward compatible implementations.
type UnimplementedSendMessageServer struct {
}

func (UnimplementedSendMessageServer) SendTextMsg(context.Context, *TextMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTextMsg not implemented")
}
func (UnimplementedSendMessageServer) SendMarkdownMsg(context.Context, *MarkdownMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMarkdownMsg not implemented")
}
func (UnimplementedSendMessageServer) mustEmbedUnimplementedSendMessageServer() {}

// UnsafeSendMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMessageServer will
// result in compilation errors.
type UnsafeSendMessageServer interface {
	mustEmbedUnimplementedSendMessageServer()
}

func RegisterSendMessageServer(s grpc.ServiceRegistrar, srv SendMessageServer) {
	s.RegisterService(&SendMessage_ServiceDesc, srv)
}

func _SendMessage_SendTextMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).SendTextMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SendMessage/SendTextMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).SendTextMsg(ctx, req.(*TextMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendMessage_SendMarkdownMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkdownMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).SendMarkdownMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SendMessage/SendMarkdownMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).SendMarkdownMsg(ctx, req.(*MarkdownMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMessage_ServiceDesc is the grpc.ServiceDesc for SendMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SendMessage",
	HandlerType: (*SendMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTextMsg",
			Handler:    _SendMessage_SendTextMsg_Handler,
		},
		{
			MethodName: "SendMarkdownMsg",
			Handler:    _SendMessage_SendMarkdownMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
